# Generated by Django 4.2.11 on 2024-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselor",
            name="name",
            field=models.CharField(default="default_value_here", max_length=100),
        ),
        migrations.AddField(
            model_name="counselor",
            name="qualifications",
            field=models.TextField(default="default_value_here"),
        ),
    ]
