# Generated by Django 4.2.11 on 2024-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0002_counselor_name_counselor_qualifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="session",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
