# Generated by Django 4.2.11 on 2024-06-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0004_users_useractivatetokens_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="session_id",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="counseling.counselingsession",
            ),
            preserve_default=False,
        ),
    ]
