# Generated by Django 4.2.11 on 2024-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0005_remove_chatmessage_session_id_chatmessage_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="session",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
