# Generated by Django 4.2.11 on 2024-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_counselors"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("picture", models.FileField(upload_to="picture/")),
            ],
        ),
    ]
