# Generated by Django 4.2.11 on 2024-07-06 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0003_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="counselors",
            old_name="name",
            new_name="counselorname",
        ),
        migrations.RemoveField(
            model_name="counselors",
            name="user",
        ),
        migrations.AddField(
            model_name="counselors",
            name="age",
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counselors",
            name="email",
            field=models.EmailField(
                default="admin@sample.com", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counselors",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="counselors",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="counselors",
            name="picture",
            field=models.FileField(null=True, upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="counselors",
            name="users",
            field=models.ManyToManyField(
                related_name="counselors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
