# Generated by Django 4.2.11 on 2024-07-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0004_rename_name_counselors_counselorname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselorActivateTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(db_index=True)),
                ("expired_at", models.DateTimeField()),
                (
                    "Counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boards.counselors",
                    ),
                ),
            ],
            options={
                "db_table": "Counselor_activate_tokens",
            },
        ),
    ]
