# Generated by Django 4.2.11 on 2024-07-06 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0005_counseloractivatetokens"),
    ]

    operations = [
        migrations.RenameField(
            model_name="counseloractivatetokens",
            old_name="Counselor",
            new_name="counselor",
        ),
    ]
