# Generated by Django 4.2.11 on 2024-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_users_managers_users_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselor",
            name="is_counselor",
            field=models.BooleanField(default=False),
        ),
    ]
