# Generated by Django 4.2.11 on 2024-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_counselor_is_counselor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counselor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="counselor",
            name="is_counselor",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="counselor",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
