# Generated by Django 4.2.11 on 2024-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselor",
            name="name",
            field=models.CharField(default="default_name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counselor",
            name="picture",
            field=models.ImageField(
                default="default.jpg", upload_to="counselor_pictures/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="counselor",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
